project:
  prefix: mk

user:
  name: maxime
  surname: leriche
  imageOwner: accetto
  image: ubuntu-vnc-xfce-nodejs-g3
  tag: vnc-vscode-chromium
  gui:
    storage: 5Gi
    Env:
      VNC_RESOLUTION: 1920x1080
      VNC_PORT: 5901
      VNC_PW: headless
    Port:
        - 3000 # Nodejs
        - 5901 # VNC
  limit:
    storage: 20Gi
    cpu: "2"
    memory: 5Gi
