{{- $namespace := printf "%s-master-guac" .Values.project.prefix -}}
---
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    "helm.sh/resource-policy": keep
    "meta.helm.sh/release-namespace": {{$namespace}}
  name: {{$namespace}}