{{- $namespace := printf "%s-master-guac" .Values.project.prefix -}}
apiVersion: v1
kind: Secret
metadata:
  name: "db-secret-guac"
  namespace: {{$namespace}}
type: Opaque
data:
  POSTGRES_PASSWORD: {{.Values.postgres.password | b64enc | quote}}
  POSTGRES_USER: {{.Values.postgres.user | b64enc | quote}}
  POSTGRES_DB: {{.Values.postgres.database | b64enc | quote}}
