{{- $namespace := printf "%s-master-guac" .Values.project.prefix -}}
{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "guacamole.serviceAccountName" . }}
  namespace: {{$namespace}}
  labels:
{{ include "guacamole.labels" . | indent 4 }}
{{- end -}}
