{{- $namespace := printf "%s-master-guac" .Values.project.prefix -}}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "guacamole.fullname" . }}-guacamole
  namespace: {{$namespace}}
  labels:
{{ include "guacamole.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "guacamole.name" . }}-guacamole
    app.kubernetes.io/instance: {{ .Release.Name }}
