{{- $namespace := printf "%s-master-guac" .Values.project.prefix -}}
---
apiVersion: v1
kind: Service
metadata:
  name: "db-service-guac"
  namespace: {{$namespace}}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
      name: http
  selector:
    app: "db-deploy-guac"
