{{- $initial := initials .Values.user.name -}}
{{- $namespace := printf "%s-%s%s" .Values.project.prefix $initial .Values.user.surname -}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{printf "gui-config-%s%s" $initial .Values.user.surname}}
  namespace: {{ $namespace }}
  annotations:
    "helm.sh/resource-policy": keep
    "meta.helm.sh/release-namespace": {{ $namespace }}
  labels:
    app: {{printf "gui-config-%s%s" $initial .Values.user.surname}}
data:
  {{- range $key,$val := .Values.user.gui.Env }}
  {{$key}}: {{$val}}
  {{- end }}
