{{- $initial := initials .Values.user.name -}}
{{- $namespace := printf "%s-%s%s" .Values.project.prefix $initial .Values.user.surname -}}
---
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    "helm.sh/resource-policy": keep
    "meta.helm.sh/release-namespace": {{$namespace}}
  name: {{$namespace}}