{{- $initial := initials .Values.user.name -}}
{{- $namespace := printf "%s-%s%s" .Values.project.prefix $initial .Values.user.surname -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{printf "role-%s" $namespace}}
  namespace: {{ $namespace }}
  annotations:
    "helm.sh/resource-policy": keep
    "meta.helm.sh/release-namespace": {{$namespace}}
rules:
  - apiGroups: [ "", "extensions","apps" ]
    resources: [ "deployments","pods","configmaps", "secrets", "jobs", "DaemonSets", "ReplicaSets", "services", "ingresses","endpoints" ]
    verbs: [ "*" ]
