{{- $initial := initials .Values.user.name -}}
{{- $namespace := printf "%s-%s%s" .Values.project.prefix $initial .Values.user.surname -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: user
  namespace: {{ $namespace }}
  annotations:
    "helm.sh/resource-policy": keep
    "meta.helm.sh/release-namespace": {{$namespace}}
subjects:
  - kind: ServiceAccount
    name: {{printf "%s%s" $initial .Values.user.surname}}
roleRef:
  kind: Role
  name: role-user
  apiGroup: rbac.authorization.k8s.io
