{{- $initial := initials .Values.user.name -}}
{{- $namespace := printf "%s-%s%s" .Values.project.prefix $initial .Values.user.surname -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: user
  namespace: {{$namespace}}
automountServiceAccountToken: false
